# Generated by Django 4.2.30 on 2026-04-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('add_campaign', 'Puede agregar campañas'), ('change_campaign', 'Puede modificar campañas'), ('delete_campaign', 'Puede eliminar campañas'), ('view_campaign', 'Puede ver campañas')], 'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'default_permissions': (), 'ordering': ['nombre'], 'permissions': [('add_category', 'Puede agregar categorías'), ('change_category', 'Puede modificar categorías'), ('delete_category', 'Puede eliminar categorías'), ('view_category', 'Puede ver categorías')], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('add_donation', 'Puede registrar donaciones'), ('change_donation', 'Puede modificar donaciones'), ('delete_donation', 'Puede eliminar donaciones'), ('view_donation', 'Puede ver donaciones')], 'verbose_name': 'Donación', 'verbose_name_plural': 'Donaciones'},
        ),
    ]
