# Generated by Django 4.2.30 on 2026-04-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icono',
            field=models.CharField(choices=[('tecnologia', 'Tecnología'), ('educacion', 'Educación'), ('salud', 'Salud y Bienestar'), ('gastronomia', 'Gastronomía'), ('arte', 'Arte y Cultura'), ('deporte', 'Deporte'), ('medio_ambiente', 'Medio Ambiente'), ('comunidad', 'Comunidad'), ('emprendimiento', 'Emprendimiento'), ('musica', 'Música'), ('viaje', 'Viaje y Turismo'), ('general', 'General')], default='general', max_length=30, verbose_name='Ícono'),
        ),
    ]
